const COPY = {
  ar: {
    common: {
      loading: 'جارٍ التحميل…', loadError: 'تعذّر التحميل.', empty: 'لا نتائج.', actions: 'إجراءات',
      save: 'حفظ', cancel: 'إلغاء', edit: 'تعديل', delete: 'حذف', all: 'الكل', status: 'الحالة',
    },
    dashboard: {
      heading: 'لوحة القيادة', pendingPayments: 'مدفوعات بانتظار المراجعة',
      publishedCourses: (published, total) => `دورات منشورة (${published} من ${total})`,
      activeEnrollments: 'اشتراكات نشطة', students: 'طلاب', instructors: 'مدرّبون', users: 'إجمالي المستخدمين',
    },
    payments: {
      heading: 'المعاملات', provider: 'فواتيرك', paidCount: 'عملية مدفوعة', revenue: 'ج.م إيرادات',
      tabs: [['', 'الكل'], ['paid', 'مدفوعة'], ['pending', 'قيد الدفع'], ['failed', 'فاشلة'], ['expired', 'منتهية'], ['refunded', 'مستردة']],
      kinds: { enroll: 'اشتراك', renewal: 'تجديد', bundle: 'حزمة', video: 'فيديو' },
      statuses: { paid: 'مدفوعة', pending: 'قيد الدفع', failed: 'فاشلة', expired: 'منتهية', refunded: 'مستردة' },
      columns: ['#', 'النوع', 'الهدف', 'المبلغ', 'الطريقة', 'المرجع', 'الحالة', 'التاريخ'],
      course: 'دورة', bundle: 'حزمة', empty: 'لا معاملات.',
    },
    baytarian: {
      heading: 'توثيق الأطباء', filters: [['pending', 'قيد المراجعة'], ['approved', 'موثّق'], ['rejected', 'مرفوض'], ['', 'الكل']],
      statuses: { pending: 'قيد المراجعة', approved: 'موثّق', rejected: 'مرفوض' },
      columns: ['الطبيب', 'الحالة', 'ملاحظة', 'المستندات', 'التاريخ', 'إجراءات'], document: 'مستند',
      verify: 'توثيق', reject: 'رفض', verified: 'تم التوثيق', empty: 'لا طلبات.', openError: 'تعذّر فتح المستند',
      confirm: (name) => `توثيق ${name} كطبيب بيطري؟`, rejectReason: 'سبب الرفض (اختياري)',
    },
    hierarchy: {
      heading: 'الهيكلة', subtitle: 'المدرّبون ← الدورات ← الوحدات ← الدروس',
      description: 'عرض شجري لكل مدرّب ومحتواه. استخدم صفحة الدورات لإدارة المحتوى.',
      enrolled: 'مسجّل', noModules: 'لا وحدات', noLessons: 'لا دروس', video: 'فيديو', noVideo: 'بدون فيديو',
      noCourses: 'لا دورات لهذا المدرّب.', empty: 'لا مدرّبين بعد — أضِف مدرّباً من المستخدمين.',
      courseError: 'تعذّر تحميل الدورة', coursesError: 'تعذّر تحميل الدورات',
    },
    videoReports: {
      heading: 'مراقبة الفيديو', subtitle: 'تقارير الأمان والمشاهدة لكل جلسات فيديو بيطرة.',
      detailHeading: 'جلسة المشاهدة', back: 'العودة إلى التقارير', refresh: 'تحديث', export: 'تصدير CSV', view: 'عرض',
      loading: 'جارٍ تحميل التقرير…', empty: 'لا جلسات تطابق عوامل التصفية.', loadError: 'تعذّر تحميل تقرير الفيديو.', exportError: 'تعذّر تصدير التقرير.',
      metrics: { attempts: 'المحاولات', successful: 'جلسات ناجحة', active: 'نشطة الآن', unique_viewers: 'مشاهدون', watch_seconds: 'وقت المشاهدة', completion_rate: 'معدل الإكمال', denied: 'مرفوضة', failures: 'فشل' },
      filters: { date_from: 'من تاريخ', date_to: 'إلى تاريخ', video: 'معرّف الفيديو', category: 'الفئة', course: 'معرّف الدورة', access_type: 'نوع الوصول', viewer: 'المشاهد', status: 'الحالة', device: 'الجهاز', ip: 'عنوان IP' },
      all: 'الكل', apply: 'تطبيق', clear: 'مسح', previous: 'السابق', next: 'التالي', page: 'صفحة', of: 'من',
      columns: ['المشاهد', 'الفيديو', 'الفئة / الدورة', 'الوصول', 'الحالة', 'المشاهدة', 'الجهاز / IP', 'بدأت', 'إجراء'],
      statuses: { denied: 'مرفوضة', provider_failed: 'فشل المزوّد', issued: 'تم الإصدار', playing: 'قيد التشغيل', paused: 'متوقفة', completed: 'مكتملة', error: 'خطأ', abandoned: 'منقطعة' },
      events: { denied: 'رفض', provider_failed: 'فشل المزوّد', otp_issued: 'إصدار تصريح المشاهدة', play: 'تشغيل', pause: 'إيقاف مؤقت', resume: 'استئناف', heartbeat: 'نبضة متابعة', ended: 'انتهاء', player_error: 'خطأ المشغّل', abandoned: 'انقطاع الجلسة' },
      access: { free: 'مجاني للجميع', vet_free: 'مجاني للأطباء', baytarian: 'مدفوع للأطباء', general: 'مدفوع لغير الأطباء' },
      identity: 'هوية المشاهد', security: 'بيانات الأمان', measurements: 'قياسات المشاهدة', timeline: 'سجل الأحداث',
      labels: { name: 'الاسم', email: 'البريد', phone: 'الهاتف', video: 'الفيديو', course: 'الدورة', category: 'الفئة', access: 'الوصول', status: 'الحالة', reason: 'السبب', session: 'مرجع الجلسة', device: 'معرّف الجهاز', ip: 'عنوان IP', browser: 'المتصفح', started: 'بدأت', firstPlayed: 'أول تشغيل', lastEvent: 'آخر حدث', ended: 'انتهت', watched: 'وقت المشاهدة', covered: 'المحتوى المغطى', duration: 'المدة', completion: 'الإكمال', event: 'الحدث', position: 'الموضع', time: 'الوقت' },
    },
    articles: {
      heading: 'المحتوى والمقالات', new: 'مقال جديد', edit: 'تعديل مقال', add: 'مقال جديد',
      filters: [['', 'الكل'], ['blog', 'مدوّنة'], ['content', 'محتوى مجاني']], types: { blog: 'مدوّنة', content: 'محتوى مجاني' },
      title: 'العنوان', type: 'النوع', status: 'الحالة', actions: 'إجراءات', draft: 'مسودة', published: 'منشور',
      publish: 'نشر', hide: 'إخفاء', empty: 'لا مقالات.', deleteConfirm: (title) => `حذف «${title}»؟`,
      titleAr: 'العنوان (عربي)', titleEn: 'العنوان (إنجليزي)', excerptAr: 'المقتطف (عربي)', excerptEn: 'المقتطف (إنجليزي)',
      cover: 'رابط صورة الغلاف', contentAr: 'المحتوى (عربي)', contentEn: 'المحتوى (إنجليزي)',
    },
    users: {
      heading: 'المستخدمون', new: 'مستخدم جديد', edit: 'تعديل مستخدم',
      filters: [['', 'كل الأدوار'], ['student', 'طالب'], ['instructor', 'مدرّب'], ['admin', 'مسؤول']],
      roles: { student: 'طالب', instructor: 'مدرّب', admin: 'مسؤول' }, searchPlaceholder: 'بحث بالاسم/البريد', search: 'بحث',
      name: 'الاسم', email: 'البريد', password: 'كلمة المرور', newPassword: 'كلمة مرور جديدة (اختياري)', role: 'الدور',
      activeAccount: 'الحساب مفعّل', headline: 'المسمّى المهني (يظهر بالموقع)', bio: 'نبذة', expertise: 'مجالات الخبرة (افصل بفاصلة)',
      active: 'مفعّل', inactive: 'معطّل', activate: 'تفعيل', deactivate: 'تعطيل', empty: 'لا نتائج.',
      deleteConfirm: (name) => `حذف ${name}؟`, columns: ['الاسم', 'البريد', 'الدور', 'الحالة', 'إجراءات'],
    },
    messages: {
      heading: 'الرسائل', unread: 'غير مقروءة', empty: 'لا رسائل.', noSubject: '(بدون موضوع)',
      markRead: 'وضع كمقروءة', markUnread: 'وضع كغير مقروءة', reply: 'رد بالبريد', deleteConfirm: 'حذف الرسالة؟',
    },
    settings: {
      heading: 'إعدادات الموقع', subtitle: 'محتوى الموقع الرئيسي — يظهر مباشرةً على الصفحة العامة بعد الحفظ.',
      saved: 'تم الحفظ', saveError: 'تعذّر الحفظ.', save: 'حفظ الإعدادات',
    },
    list: {
      add: '+ إضافة', empty: 'لا عناصر بعد.', order: 'ترتيب', actions: 'إجراءات', edit: 'تعديل', delete: 'حذف',
      addTitle: 'إضافة عنصر', editTitle: 'تعديل عنصر', save: 'حفظ', cancel: 'إلغاء',
      moveUp: (name) => `نقل ${name} لأعلى`, moveDown: (name) => `نقل ${name} لأسفل`,
    },
  },
  en: {
    common: {
      loading: 'Loading…', loadError: 'Unable to load.', empty: 'No results.', actions: 'Actions',
      save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', all: 'All', status: 'Status',
    },
    dashboard: {
      heading: 'Dashboard', pendingPayments: 'Payments awaiting review',
      publishedCourses: (published, total) => `Published courses (${published} of ${total})`,
      activeEnrollments: 'Active enrollments', students: 'Students', instructors: 'Instructors', users: 'Total users',
    },
    payments: {
      heading: 'Payments', provider: 'Fawaterak', paidCount: 'paid payments', revenue: 'EGP revenue',
      tabs: [['', 'All'], ['paid', 'Paid'], ['pending', 'Pending'], ['failed', 'Failed'], ['expired', 'Expired'], ['refunded', 'Refunded']],
      kinds: { enroll: 'Enrollment', renewal: 'Renewal', bundle: 'Bundle', video: 'Video' },
      statuses: { paid: 'Paid', pending: 'Pending', failed: 'Failed', expired: 'Expired', refunded: 'Refunded' },
      columns: ['#', 'Type', 'Target', 'Amount', 'Method', 'Reference', 'Status', 'Date'],
      course: 'Course', bundle: 'Bundle', empty: 'No payments.',
    },
    baytarian: {
      heading: 'Veterinarian verification', filters: [['pending', 'Pending review'], ['approved', 'Verified'], ['rejected', 'Rejected'], ['', 'All']],
      statuses: { pending: 'Pending review', approved: 'Verified', rejected: 'Rejected' },
      columns: ['Veterinarian', 'Status', 'Note', 'Documents', 'Date', 'Actions'], document: 'Document',
      verify: 'Verify', reject: 'Reject', verified: 'Veterinarian verified', empty: 'No requests.', openError: 'Unable to open document',
      confirm: (name) => `Verify ${name} as a veterinarian?`, rejectReason: 'Rejection reason (optional)',
    },
    hierarchy: {
      heading: 'Hierarchy', subtitle: 'Instructors → courses → modules → lessons',
      description: 'Browse each instructor and their content. Use Courses to manage content.',
      enrolled: 'enrolled', noModules: 'No modules', noLessons: 'No lessons', video: 'Video', noVideo: 'No video',
      noCourses: 'No courses for this instructor.', empty: 'No instructors yet — add one from Users.',
      courseError: 'Unable to load course', coursesError: 'Unable to load courses',
    },
    videoReports: {
      heading: 'Video monitoring', subtitle: 'Security and viewing reports for every Baytara video session.',
      detailHeading: 'Playback session', back: 'Back to reports', refresh: 'Refresh', export: 'Export CSV', view: 'View',
      loading: 'Loading report…', empty: 'No sessions match these filters.', loadError: 'Unable to load the video report.', exportError: 'Unable to export the report.',
      metrics: { attempts: 'Attempts', successful: 'Successful', active: 'Active now', unique_viewers: 'Viewers', watch_seconds: 'Watch time', completion_rate: 'Completion rate', denied: 'Denied', failures: 'Failures' },
      filters: { date_from: 'From date', date_to: 'To date', video: 'Video ID', category: 'Category', course: 'Course ID', access_type: 'Access type', viewer: 'Viewer', status: 'Status', device: 'Device', ip: 'IP address' },
      all: 'All', apply: 'Apply', clear: 'Clear', previous: 'Previous', next: 'Next', page: 'Page', of: 'of',
      columns: ['Viewer', 'Video', 'Category / course', 'Access', 'Status', 'Watched', 'Device / IP', 'Started', 'Action'],
      statuses: { denied: 'Denied', provider_failed: 'Provider failed', issued: 'Issued', playing: 'Playing', paused: 'Paused', completed: 'Completed', error: 'Error', abandoned: 'Abandoned' },
      events: { denied: 'Denied', provider_failed: 'Provider failed', otp_issued: 'OTP issued', play: 'Play', pause: 'Pause', resume: 'Resume', heartbeat: 'Heartbeat', ended: 'Ended', player_error: 'Player error', abandoned: 'Session abandoned' },
      access: { free: 'Free for everyone', vet_free: 'Free for veterinarians', baytarian: 'Paid for veterinarians', general: 'Paid for non-veterinarians' },
      identity: 'Viewer identity', security: 'Security facts', measurements: 'Viewing measurements', timeline: 'Event timeline',
      labels: { name: 'Name', email: 'Email', phone: 'Phone', video: 'Video', course: 'Course', category: 'Category', access: 'Access', status: 'Status', reason: 'Reason', session: 'Session reference', device: 'Device ID', ip: 'IP address', browser: 'Browser', started: 'Started', firstPlayed: 'First played', lastEvent: 'Last event', ended: 'Ended', watched: 'Watched', covered: 'Covered', duration: 'Duration', completion: 'Completion', event: 'Event', position: 'Position', time: 'Time' },
    },
    articles: {
      heading: 'Content and articles', new: 'New article', edit: 'Edit article', add: 'New article',
      filters: [['', 'All'], ['blog', 'Blog'], ['content', 'Free content']], types: { blog: 'Blog', content: 'Free content' },
      title: 'Title', type: 'Type', status: 'Status', actions: 'Actions', draft: 'Draft', published: 'Published',
      publish: 'Publish', hide: 'Unpublish', empty: 'No articles.', deleteConfirm: (title) => `Delete “${title}”?`,
      titleAr: 'Arabic title', titleEn: 'English title', excerptAr: 'Arabic excerpt', excerptEn: 'English excerpt',
      cover: 'Cover image URL', contentAr: 'Arabic content', contentEn: 'English content',
    },
    users: {
      heading: 'Users', new: 'New user', edit: 'Edit user',
      filters: [['', 'All roles'], ['student', 'Student'], ['instructor', 'Instructor'], ['admin', 'Administrator']],
      roles: { student: 'Student', instructor: 'Instructor', admin: 'Administrator' }, searchPlaceholder: 'Search name or email', search: 'Search',
      name: 'Name', email: 'Email', password: 'Password', newPassword: 'New password (optional)', role: 'Role',
      activeAccount: 'Account is active', headline: 'Professional title (shown publicly)', bio: 'Bio', expertise: 'Expertise (comma separated)',
      active: 'Active', inactive: 'Inactive', activate: 'Activate', deactivate: 'Deactivate', empty: 'No results.',
      deleteConfirm: (name) => `Delete ${name}?`, columns: ['Name', 'Email', 'Role', 'Status', 'Actions'],
    },
    messages: {
      heading: 'Messages', unread: 'unread', empty: 'No messages.', noSubject: '(No subject)',
      markRead: 'Mark as read', markUnread: 'Mark as unread', reply: 'Reply by email', deleteConfirm: 'Delete this message?',
    },
    settings: {
      heading: 'Site settings', subtitle: 'Public website content updates immediately after you save.',
      saved: 'Saved', saveError: 'Unable to save.', save: 'Save settings',
    },
    list: {
      add: '+ Add', empty: 'No items yet.', order: 'Order', actions: 'Actions', edit: 'Edit', delete: 'Delete',
      addTitle: 'Add item', editTitle: 'Edit item', save: 'Save', cancel: 'Cancel',
      moveUp: (name) => `Move ${name} up`, moveDown: (name) => `Move ${name} down`,
    },
  },
};

export function pageCopy(page, language = 'ar') {
  return COPY[language]?.[page] || COPY.ar[page] || {};
}
