const COPY = {
  ar: {
    common: {
      loading: 'جارٍ التحميل…', loadError: 'تعذّر التحميل.', empty: 'لا نتائج.', actions: 'إجراءات',
      save: 'حفظ', cancel: 'إلغاء', edit: 'تعديل', delete: 'حذف', all: 'الكل', status: 'الحالة',
    },
    dashboard: {
      heading: 'لوحة القيادة',
      subtitle: 'اضغط على أي رقم للانتقال إلى تفاصيله.',
      egp: 'ج.م',
      storageTitle: 'مساحة الفيديوهات على الخادم',
      storageVideos: 'حجم الفيديوهات', storageCount: 'عدد الفيديوهات المرفوعة',
      storageFree: 'المساحة المتاحة', storageDisk: 'إجمالي القرص',
      storageOther: 'مستخدَم بواسطة النظام', storageLargest: 'الأكبر حجماً',
      storageSize: 'الحجم', storageOrphan: 'مجلد بلا فيديو', storagePath: 'مسار التخزين',
      groups: {
        attention: 'يحتاج إجراءً', money: 'المدفوعات والإيرادات',
        learners: 'المتعلّمون', catalog: 'المحتوى', people: 'الحسابات',
      },
      pendingPayments: 'مدفوعات بانتظار المراجعة',
      pendingBaytarian: 'طلبات توثيق معلّقة', unreadMessages: 'رسائل غير مقروءة',
      videosNoProvider: 'فيديوهات بلا ملف مرفوع', videosUnassigned: 'فيديوهات غير معيّنة لدورة',
      revenue: 'الإيرادات (بعد الاسترداد)', refundedAmount: 'إجمالي المسترد',
      paidPayments: 'عمليات مدفوعة', refundedPayments: 'عمليات مستردة بالكامل',
      partiallyRefunded: 'استرداد جزئي', failedPayments: 'عمليات فاشلة',
      activeEnrollments: 'اشتراكات نشطة', expiredEnrollments: 'اشتراكات منتهية',
      cancelledEnrollments: 'اشتراكات ملغاة', certificates: 'شهادات صادرة', reviews: 'آراء',
      publishedCourses: 'دورات منشورة', draftCourses: 'دورات مسودة', unpublishedCourses: 'دورات غير منشورة',
      publishedVideos: 'فيديوهات منشورة', draftVideos: 'فيديوهات مسودة',
      bundles: 'حزم', paths: 'مسارات', categories: 'فئات', articles: 'مقالات',
      students: 'طلاب', instructors: 'محاضرون', admins: 'مسؤولون',
      users: 'إجمالي المستخدمين', inactiveUsers: 'حسابات معطّلة',
    },
    payments: {
      heading: 'المعاملات', provider: 'فواتيرك', paidCount: 'عملية مدفوعة', revenue: 'ج.م إيرادات',
      tabs: [['', 'الكل'], ['paid', 'مدفوعة'], ['pending', 'قيد الدفع'], ['failed', 'فاشلة'], ['expired', 'منتهية'], ['refunded', 'مستردة']],
      kinds: { enroll: 'اشتراك', renewal: 'تجديد', bundle: 'حزمة', video: 'فيديو' },
      statuses: { paid: 'مدفوعة', pending: 'قيد الدفع', failed: 'فاشلة', expired: 'منتهية', refunded: 'مستردة' },
      columns: ['#', 'النوع', 'الهدف', 'المبلغ', 'الطريقة', 'المرجع', 'الحالة', 'التاريخ'],
      course: 'دورة', bundle: 'حزمة', empty: 'لا معاملات.',
    },
    baytarian: {
      heading: 'توثيق الأطباء', filters: [['pending', 'قيد المراجعة'], ['approved', 'موثّق'], ['rejected', 'مرفوض'], ['', 'الكل']],
      statuses: { pending: 'قيد المراجعة', approved: 'موثّق', rejected: 'مرفوض' },
      columns: ['الطبيب', 'الحالة', 'الطريق وما قرأه الذكاء الاصطناعي', 'عدد المستندات', 'التاريخ', 'إجراءات'], document: 'مستند',
      details: 'التفاصيل', close: 'إغلاق', yes: 'نعم', no: 'لا',
      aiHeading: 'ما قرأه الذكاء الاصطناعي', parsedHeading: 'حقول بطاقة النقابة', ocrHeading: 'النص الخام المقروء',
      noVerdict: 'لم تُقرأ بالذكاء الاصطناعي — رفع يدوي.', noDocuments: 'لا مستندات مرفقة.',
      loadingDocuments: 'جارٍ تحميل المستندات…', openFull: 'فتح الصورة بالحجم الكامل',
      verdictLabels: {
        document_type: 'نوع المستند', issuer: 'الجهة المُصدِرة', holder_name: 'الاسم على المستند',
        name_match: 'مطابقة الاسم', national_id: 'الرقم القومي', occupation: 'الوظيفة',
        occupation_is_veterinarian: 'الوظيفة طبيب بيطري', is_veterinary_student: 'طالب طب بيطري',
        expired: 'منتهي الصلاحية', tampered: 'يبدو معدّلاً', confidence: 'الثقة',
      },
      nameMatch: { same: 'مطابق', similar: 'نفس الشخص بصيغة مختلفة', different: 'شخص آخر', unreadable: 'غير مقروء' },
      verify: 'توثيق', reject: 'رفض', revoke: 'سحب التوثيق',
      verified: 'تم التوثيق', revoked: 'تم سحب التوثيق', empty: 'لا طلبات.', openError: 'تعذّر فتح المستند',
      confirm: (name) => `توثيق ${name}؟`,
      rejectReason: 'سبب الرفض (اختياري)', revokeReason: 'سبب سحب التوثيق',
      routes: { manual: 'رفع يدوي', syndicate_card: 'بطاقة النقابة', national_id: 'بطاقة الرقم القومي', other: 'مستند آخر', admin: 'توثيق من الإدارة' },
      verifyDirect: 'توثيق مستخدم بدون مستند',
      verifyDirectTitle: 'توثيق على مسؤولية الإدارة',
      verifyDirectHint: 'ابحث عن الحساب ووثّقه مباشرة بدون مستند. يظهر الطلب في هذه القائمة باسم «توثيق من الإدارة» ويمكن سحبه لاحقاً.',
      verifyDirectSearch: 'ابحث بالاسم أو البريد', verifyDirectSearchBtn: 'بحث',
      verifyDirectGrant: 'نوع التوثيق',
      verifyDirectNote: 'سبب التوثيق (اختياري)',
      verifyDirectConfirm: (name) => `توثيق ${name} بدون مستند؟`,
      verifyDirectDone: 'تم توثيق الحساب',
      alreadyVerified: 'موثّق بالفعل',
      noUsers: 'لا نتائج.',
      grants: { baytarian: 'طبيب بيطري مرخّص', vet_student: 'طالب طب بيطري' },
      autoApproved: 'وثّقه النظام', spotCheck: 'مطلوب فحص عشوائي',
      confidence: { high: 'ثقة عالية', medium: 'ثقة متوسطة', low: 'ثقة منخفضة' },
    },
    hierarchy: {
      heading: 'الهيكلة', subtitle: 'المدرّبون ← الدورات ← الوحدات ← الدروس',
      description: 'عرض شجري لكل مدرّب ومحتواه. استخدم صفحة الدورات لإدارة المحتوى.',
      enrolled: 'مسجّل', noModules: 'لا وحدات', noLessons: 'لا دروس', video: 'فيديو', noVideo: 'بدون فيديو',
      noCourses: 'لا دورات لهذا المدرّب.', empty: 'لا مدرّبين بعد — أضِف مدرّباً من المستخدمين.',
      courseError: 'تعذّر تحميل الدورة', coursesError: 'تعذّر تحميل الدورات',
    },
    videoReports: {
      heading: 'مراقبة الفيديو', subtitle: 'تقارير الأمان والمشاهدة لكل جلسات فيديو بيطرة.',
      detailHeading: 'جلسة المشاهدة', back: 'العودة إلى التقارير', refresh: 'تحديث', export: 'تصدير CSV', view: 'عرض',
      loading: 'جارٍ تحميل التقرير…', empty: 'لا جلسات تطابق عوامل التصفية.', loadError: 'تعذّر تحميل تقرير الفيديو.', exportError: 'تعذّر تصدير التقرير.',
      metrics: { attempts: 'المحاولات', successful: 'جلسات ناجحة', active: 'نشطة الآن', unique_viewers: 'مشاهدون', watch_seconds: 'وقت المشاهدة', completion_rate: 'معدل الإكمال', denied: 'مرفوضة', failures: 'فشل' },
      filters: { date_from: 'من تاريخ', date_to: 'إلى تاريخ', video: 'معرّف الفيديو', category: 'الفئة', course: 'معرّف الدورة', access_type: 'نوع الوصول', viewer: 'المشاهد', status: 'الحالة', device: 'الجهاز', ip: 'عنوان IP' },
      all: 'الكل', apply: 'تطبيق', clear: 'مسح', previous: 'السابق', next: 'التالي', page: 'صفحة', of: 'من',
      columns: ['المشاهد', 'الفيديو', 'الفئة / الدورة', 'الوصول', 'الحالة', 'المشاهدة', 'الجهاز / IP', 'بدأت', 'إجراء'],
      statuses: { denied: 'مرفوضة', provider_failed: 'فشل المزوّد', issued: 'تم الإصدار', playing: 'قيد التشغيل', paused: 'متوقفة', completed: 'مكتملة', error: 'خطأ', abandoned: 'منقطعة' },
      events: { denied: 'رفض', provider_failed: 'فشل المزوّد', otp_issued: 'إصدار تصريح المشاهدة', play: 'تشغيل', pause: 'إيقاف مؤقت', resume: 'استئناف', heartbeat: 'نبضة متابعة', ended: 'انتهاء', player_error: 'خطأ المشغّل', abandoned: 'انقطاع الجلسة' },
      access: { free: 'مجاني للجميع', vet_free: 'مجاني للأطباء', baytarian: 'مدفوع للأطباء', general: 'مدفوع لغير الأطباء' },
      identity: 'هوية المشاهد', security: 'بيانات الأمان', measurements: 'قياسات المشاهدة', timeline: 'سجل الأحداث',
      labels: { name: 'الاسم', email: 'البريد', phone: 'الهاتف', video: 'الفيديو', course: 'الدورة', category: 'الفئة', access: 'الوصول', status: 'الحالة', reason: 'السبب', session: 'مرجع الجلسة', device: 'معرّف الجهاز', ip: 'عنوان IP', browser: 'المتصفح', started: 'بدأت', firstPlayed: 'أول تشغيل', lastEvent: 'آخر حدث', ended: 'انتهت', watched: 'وقت المشاهدة', covered: 'المحتوى المغطى', duration: 'المدة', completion: 'الإكمال', event: 'الحدث', position: 'الموضع', time: 'الوقت' },
    },
    articles: {
      heading: 'المحتوى والمقالات', new: 'مقال جديد', edit: 'تعديل مقال', add: 'مقال جديد',
      filters: [['', 'الكل'], ['blog', 'مدوّنة'], ['content', 'محتوى مجاني']], types: { blog: 'مدوّنة', content: 'محتوى مجاني' },
      title: 'العنوان', type: 'النوع', status: 'الحالة', actions: 'إجراءات', draft: 'مسودة', published: 'منشور',
      publish: 'نشر', hide: 'إخفاء', empty: 'لا مقالات.', deleteConfirm: (title) => `حذف «${title}»؟`,
      titleAr: 'العنوان (عربي)', titleEn: 'العنوان (إنجليزي)', excerptAr: 'المقتطف (عربي)', excerptEn: 'المقتطف (إنجليزي)',
      cover: 'رابط صورة الغلاف', contentAr: 'المحتوى (عربي)', contentEn: 'المحتوى (إنجليزي)',
    },
    enrollments: {
      heading: 'التسجيلات', subtitle: 'كل تسجيلات المتعلّمين في الدورات — ابحث، وألغِ تسجيلاً مع ذكر السبب.',
      searchPlaceholder: 'بحث باسم المتعلّم أو بريده أو اسم الدورة', allStatuses: 'كل الحالات',
      columns: ['المتعلّم', 'الدورة', 'المصدر', 'المدفوع', 'تاريخ التسجيل', 'الحالة', 'إجراءات'],
      statuses: { active: 'نشط', cancelled: 'ملغى', expired: 'منتهي' },
      sources: { free: 'مجاني', purchase: 'شراء', bundle: 'حزمة', admin: 'إداري' },
      empty: 'لا تسجيلات مطابقة.', unenroll: 'إلغاء التسجيل',
      totalCount: (n) => `${n} تسجيل`,
      previous: 'السابق', next: 'التالي',
      refundedLabel: (amount) => `مسترد: ${amount}`,
      cancelTitle: (learner, course) => `إلغاء تسجيل ${learner} في «${course}»`,
      reason: 'سبب الإلغاء', reasonPlaceholder: 'مثال: شراء مكرر، طلب المتعلّم، خطأ إداري',
      reasonShownToLearner: 'يظهر هذا السبب للمتعلّم في إشعار داخل الموقع.',
      reasonRequired: 'اكتب سبب الإلغاء.',
      refund: 'استرداد المبلغ',
      refundManual: 'لا يُحوَّل أي مبلغ تلقائياً. هذا تسجيل للقرار فقط — يجب إعادة المبلغ يدوياً عبر فواتيرك أو إنستاباي.',
      paidSeat: (amount, date) => `مدفوع: ${amount} بتاريخ ${date}`,
      refundNone: 'بدون استرداد', refundPercent: 'نسبة %', refundAmount: 'مبلغ محدد',
      refundPreview: (value, remaining) => `سيُسجَّل استرداد ${value} — المتاح للاسترداد ${remaining}`,
      refundInvalid: 'أدخل قيمة استرداد صحيحة.',
      refundTooBig: (remaining, currency) => `المبلغ أكبر من المتاح للاسترداد (${remaining} ${currency || 'ج.م'}).`,
      noPayment: 'لا توجد معاملة دفع مرتبطة بهذا التسجيل.',
      confirmCancel: 'تأكيد الإلغاء', cancelled: 'تم إلغاء التسجيل.',
      errors: {
        reason_required: 'اكتب سبب الإلغاء.',
        already_cancelled: 'هذا التسجيل ملغى بالفعل.',
        no_payment_to_refund: 'لا توجد معاملة دفع لاستردادها.',
        refund_exceeds_payment: 'المبلغ أكبر من المتاح للاسترداد.',
        invalid_refund_amount: 'قيمة الاسترداد غير صحيحة.',
        invalid_refund_percent: 'النسبة يجب أن تكون بين 1 و100.',
      },
    },
    instructors: {
      heading: 'المحاضرون', new: 'محاضر جديد', edit: (name) => `تعديل المحاضر — ${name}`,
      searchPlaceholder: 'بحث بالاسم/البريد', search: 'بحث',
      photo: 'صورة المحاضر', photoHint: 'JPG / PNG / WebP — تظهر في صفحة المحاضر بالموقع', removePhoto: 'حذف الصورة',
      uploadError: 'تعذّر رفع الصورة.',
      name: 'الاسم', email: 'البريد', password: 'كلمة المرور', newPassword: 'كلمة مرور جديدة (اختياري)',
      phone: 'رقم الهاتف (داخلي — لا يظهر بالموقع)',
      headline: 'المسمّى المهني (يظهر تحت الاسم)',
      headlinePlaceholder: 'مثال: الأستاذ بمعهد بحوث تناسليات الهرم واستشاري الخيول',
      section: 'القسم', noSection: 'بدون قسم',
      bio: 'نبذة (تظهر كاملة بصفحة المحاضر)',
      expertise: 'مجالات الخبرة (افصل بفاصلة)', expertisePlaceholder: 'الخيول، التناسليات، مزارع الحلاب',
      activeAccount: 'الحساب مفعّل (يظهر بالموقع)',
      permissions: 'صلاحيات الفيديو', canAdd: 'إضافة فيديو', canEdit: 'تعديل فيديو', canDelete: 'حذف فيديو',
      columns: ['المحاضر', 'القسم', 'الدورات', 'ناقص بالملف', 'الحالة', 'إجراءات'],
      complete: 'مكتمل', missing: { photo: 'صورة', headline: 'مسمّى', bio: 'نبذة', expertise: 'خبرات', section: 'قسم' },
      active: 'مفعّل', inactive: 'معطّل', empty: 'لا محاضرين بعد.',
      deleteConfirm: (name) => `حذف ${name}؟`,
      deactivate: 'تعطيل', activate: 'تفعيل',
      invalidEmail: 'أدخل بريداً إلكترونياً صحيحاً — بدون كلمات إضافية مثل «email:».',
      deactivateConfirm: (name) => `تعطيل ${name}؟ لن يستطيع الدخول ولن يظهر في قوائم الإسناد، ويبقى محتواه كما هو.`,
      activateConfirm: (name) => `تفعيل ${name}؟`,
      statusError: 'تعذّر تغيير حالة الحساب.',
      blockedByContent: (courses, videos) =>
        `لا يمكن الحذف: هذا المحاضر يملك ${courses} دورة و${videos} فيديو. أعد إسنادها إلى محاضر آخر أولاً، أو عطّل الحساب بدلاً من حذفه.`,
    },
    users: {
      heading: 'المستخدمون', new: 'مستخدم جديد', edit: 'تعديل مستخدم',
      filters: [['', 'كل الأدوار'], ['student', 'طالب'], ['instructor', 'مدرّب'], ['admin', 'مسؤول']],
      roles: { student: 'طالب', instructor: 'مدرّب', admin: 'مسؤول' }, searchPlaceholder: 'بحث بالاسم/البريد', search: 'بحث',
      name: 'الاسم', email: 'البريد', password: 'كلمة المرور', newPassword: 'كلمة مرور جديدة (اختياري)', role: 'الدور',
      activeAccount: 'الحساب مفعّل', headline: 'المسمّى المهني (يظهر بالموقع)', bio: 'نبذة', expertise: 'مجالات الخبرة (افصل بفاصلة)',
      instructorProfileHint: 'الصورة والمسمّى والنبذة والخبرات والقسم تُدار من صفحة «المحاضرون».',
      active: 'مفعّل', inactive: 'معطّل', activate: 'تفعيل', deactivate: 'تعطيل', empty: 'لا نتائج.',
      deleteConfirm: (name) => `حذف ${name}؟`, columns: ['الاسم', 'البريد', 'الدور', 'الحالة', 'إجراءات'],
    },
    messages: {
      heading: 'الرسائل', unread: 'غير مقروءة', empty: 'لا رسائل.', noSubject: '(بدون موضوع)',
      markRead: 'وضع كمقروءة', markUnread: 'وضع كغير مقروءة', reply: 'رد بالبريد', deleteConfirm: 'حذف الرسالة؟',
    },
    settings: {
      heading: 'إعدادات الموقع', subtitle: 'محتوى الموقع الرئيسي — يظهر مباشرةً على الصفحة العامة بعد الحفظ.',
      saved: 'تم الحفظ', saveError: 'تعذّر الحفظ.', save: 'حفظ الإعدادات',
    },
    list: {
      add: '+ إضافة', empty: 'لا عناصر بعد.', order: 'ترتيب', actions: 'إجراءات', edit: 'تعديل', delete: 'حذف',
      addTitle: 'إضافة عنصر', editTitle: 'تعديل عنصر', save: 'حفظ', cancel: 'إلغاء',
      moveUp: (name) => `نقل ${name} لأعلى`, moveDown: (name) => `نقل ${name} لأسفل`,
    },
  },
  en: {
    common: {
      loading: 'Loading…', loadError: 'Unable to load.', empty: 'No results.', actions: 'Actions',
      save: 'Save', cancel: 'Cancel', edit: 'Edit', delete: 'Delete', all: 'All', status: 'Status',
    },
    dashboard: {
      heading: 'Dashboard',
      subtitle: 'Press any number to open what it counts.',
      egp: 'EGP',
      storageTitle: 'Video storage on the server',
      storageVideos: 'Videos on disk', storageCount: 'Uploaded videos',
      storageFree: 'Free space', storageDisk: 'Disk total',
      storageOther: 'Used by everything else', storageLargest: 'Largest',
      storageSize: 'Size', storageOrphan: 'Folder with no video', storagePath: 'Storage path',
      groups: {
        attention: 'Needs action', money: 'Payments and revenue',
        learners: 'Learners', catalog: 'Content', people: 'Accounts',
      },
      pendingPayments: 'Payments awaiting review',
      pendingBaytarian: 'Verification requests pending', unreadMessages: 'Unread messages',
      videosNoProvider: 'Videos with no file uploaded', videosUnassigned: 'Videos in no course',
      revenue: 'Revenue (net of refunds)', refundedAmount: 'Total refunded',
      paidPayments: 'Paid payments', refundedPayments: 'Fully refunded',
      partiallyRefunded: 'Partially refunded', failedPayments: 'Failed payments',
      activeEnrollments: 'Active enrollments', expiredEnrollments: 'Expired enrollments',
      cancelledEnrollments: 'Cancelled enrollments', certificates: 'Certificates issued', reviews: 'Reviews',
      publishedCourses: 'Published courses', draftCourses: 'Draft courses', unpublishedCourses: 'Unpublished courses',
      publishedVideos: 'Published videos', draftVideos: 'Draft videos',
      bundles: 'Bundles', paths: 'Paths', categories: 'Categories', articles: 'Articles',
      students: 'Students', instructors: 'Instructors', admins: 'Admins',
      users: 'Total users', inactiveUsers: 'Deactivated accounts',
    },
    payments: {
      heading: 'Payments', provider: 'Fawaterak', paidCount: 'paid payments', revenue: 'EGP revenue',
      tabs: [['', 'All'], ['paid', 'Paid'], ['pending', 'Pending'], ['failed', 'Failed'], ['expired', 'Expired'], ['refunded', 'Refunded']],
      kinds: { enroll: 'Enrollment', renewal: 'Renewal', bundle: 'Bundle', video: 'Video' },
      statuses: { paid: 'Paid', pending: 'Pending', failed: 'Failed', expired: 'Expired', refunded: 'Refunded' },
      columns: ['#', 'Type', 'Target', 'Amount', 'Method', 'Reference', 'Status', 'Date'],
      course: 'Course', bundle: 'Bundle', empty: 'No payments.',
    },
    baytarian: {
      heading: 'Veterinarian verification', filters: [['pending', 'Pending review'], ['approved', 'Verified'], ['rejected', 'Rejected'], ['', 'All']],
      statuses: { pending: 'Pending review', approved: 'Verified', rejected: 'Rejected' },
      columns: ['Veterinarian', 'Status', 'Route and what the AI read', 'Documents', 'Date', 'Actions'], document: 'Document',
      details: 'Details', close: 'Close', yes: 'Yes', no: 'No',
      aiHeading: 'What the AI read', parsedHeading: 'Syndicate card fields', ocrHeading: 'Raw text read',
      noVerdict: 'Not read by AI — manual upload.', noDocuments: 'No documents attached.',
      loadingDocuments: 'Loading documents…', openFull: 'Open the image full size',
      verdictLabels: {
        document_type: 'Document type', issuer: 'Issuer', holder_name: 'Name on document',
        name_match: 'Name match', national_id: 'National ID', occupation: 'Occupation',
        occupation_is_veterinarian: 'Occupation is veterinarian', is_veterinary_student: 'Veterinary student',
        expired: 'Expired', tampered: 'Looks edited', confidence: 'Confidence',
      },
      nameMatch: { same: 'Same', similar: 'Same person, written differently', different: 'A different person', unreadable: 'Unreadable' },
      verify: 'Verify', reject: 'Reject', revoke: 'Revoke',
      verified: 'Veterinarian verified', revoked: 'Verification revoked', empty: 'No requests.', openError: 'Unable to open document',
      confirm: (name) => `Verify ${name}?`,
      rejectReason: 'Rejection reason (optional)', revokeReason: 'Why is this being revoked?',
      routes: { manual: 'Manual upload', syndicate_card: 'Syndicate card', national_id: 'National ID', other: 'Other document', admin: 'Verified by admin' },
      verifyDirect: 'Verify a user with no document',
      verifyDirectTitle: 'Verify on the admin\'s authority',
      verifyDirectHint: 'Find the account and verify it directly, with no document. It appears in this list as "Verified by admin" and can be revoked later.',
      verifyDirectSearch: 'Search by name or email', verifyDirectSearchBtn: 'Search',
      verifyDirectGrant: 'Verification type',
      verifyDirectNote: 'Reason (optional)',
      verifyDirectConfirm: (name) => `Verify ${name} with no document?`,
      verifyDirectDone: 'Account verified',
      alreadyVerified: 'Already verified',
      noUsers: 'No results.',
      grants: { baytarian: 'Licensed veterinarian', vet_student: 'Veterinary student' },
      autoApproved: 'Verified by the system', spotCheck: 'Flagged for spot check',
      confidence: { high: 'High confidence', medium: 'Medium confidence', low: 'Low confidence' },
    },
    hierarchy: {
      heading: 'Hierarchy', subtitle: 'Instructors → courses → modules → lessons',
      description: 'Browse each instructor and their content. Use Courses to manage content.',
      enrolled: 'enrolled', noModules: 'No modules', noLessons: 'No lessons', video: 'Video', noVideo: 'No video',
      noCourses: 'No courses for this instructor.', empty: 'No instructors yet — add one from Users.',
      courseError: 'Unable to load course', coursesError: 'Unable to load courses',
    },
    videoReports: {
      heading: 'Video monitoring', subtitle: 'Security and viewing reports for every Baytara video session.',
      detailHeading: 'Playback session', back: 'Back to reports', refresh: 'Refresh', export: 'Export CSV', view: 'View',
      loading: 'Loading report…', empty: 'No sessions match these filters.', loadError: 'Unable to load the video report.', exportError: 'Unable to export the report.',
      metrics: { attempts: 'Attempts', successful: 'Successful', active: 'Active now', unique_viewers: 'Viewers', watch_seconds: 'Watch time', completion_rate: 'Completion rate', denied: 'Denied', failures: 'Failures' },
      filters: { date_from: 'From date', date_to: 'To date', video: 'Video ID', category: 'Category', course: 'Course ID', access_type: 'Access type', viewer: 'Viewer', status: 'Status', device: 'Device', ip: 'IP address' },
      all: 'All', apply: 'Apply', clear: 'Clear', previous: 'Previous', next: 'Next', page: 'Page', of: 'of',
      columns: ['Viewer', 'Video', 'Category / course', 'Access', 'Status', 'Watched', 'Device / IP', 'Started', 'Action'],
      statuses: { denied: 'Denied', provider_failed: 'Provider failed', issued: 'Issued', playing: 'Playing', paused: 'Paused', completed: 'Completed', error: 'Error', abandoned: 'Abandoned' },
      events: { denied: 'Denied', provider_failed: 'Provider failed', otp_issued: 'OTP issued', play: 'Play', pause: 'Pause', resume: 'Resume', heartbeat: 'Heartbeat', ended: 'Ended', player_error: 'Player error', abandoned: 'Session abandoned' },
      access: { free: 'Free for everyone', vet_free: 'Free for veterinarians', baytarian: 'Paid for veterinarians', general: 'Paid for non-veterinarians' },
      identity: 'Viewer identity', security: 'Security facts', measurements: 'Viewing measurements', timeline: 'Event timeline',
      labels: { name: 'Name', email: 'Email', phone: 'Phone', video: 'Video', course: 'Course', category: 'Category', access: 'Access', status: 'Status', reason: 'Reason', session: 'Session reference', device: 'Device ID', ip: 'IP address', browser: 'Browser', started: 'Started', firstPlayed: 'First played', lastEvent: 'Last event', ended: 'Ended', watched: 'Watched', covered: 'Covered', duration: 'Duration', completion: 'Completion', event: 'Event', position: 'Position', time: 'Time' },
    },
    articles: {
      heading: 'Content and articles', new: 'New article', edit: 'Edit article', add: 'New article',
      filters: [['', 'All'], ['blog', 'Blog'], ['content', 'Free content']], types: { blog: 'Blog', content: 'Free content' },
      title: 'Title', type: 'Type', status: 'Status', actions: 'Actions', draft: 'Draft', published: 'Published',
      publish: 'Publish', hide: 'Unpublish', empty: 'No articles.', deleteConfirm: (title) => `Delete “${title}”?`,
      titleAr: 'Arabic title', titleEn: 'English title', excerptAr: 'Arabic excerpt', excerptEn: 'English excerpt',
      cover: 'Cover image URL', contentAr: 'Arabic content', contentEn: 'English content',
    },
    enrollments: {
      heading: 'Enrollments', subtitle: 'Every learner enrolled in a course — search, and un-enroll with a reason.',
      searchPlaceholder: 'Search by learner name, email or course', allStatuses: 'All statuses',
      columns: ['Learner', 'Course', 'Source', 'Paid', 'Enrolled', 'Status', 'Actions'],
      statuses: { active: 'Active', cancelled: 'Cancelled', expired: 'Expired' },
      sources: { free: 'Free', purchase: 'Purchase', bundle: 'Bundle', admin: 'Admin' },
      empty: 'No matching enrollments.', unenroll: 'Un-enroll',
      totalCount: (n) => `${n} enrollment(s)`,
      previous: 'Previous', next: 'Next',
      refundedLabel: (amount) => `Refunded: ${amount}`,
      cancelTitle: (learner, course) => `Un-enroll ${learner} from "${course}"`,
      reason: 'Reason', reasonPlaceholder: 'e.g. duplicate purchase, learner request, admin error',
      reasonShownToLearner: 'This reason is shown to the learner in an in-app notification.',
      reasonRequired: 'Write a reason.',
      refund: 'Refund',
      refundManual: 'No money is transferred automatically. This records the decision only — the amount must be returned by hand through Fawaterak or InstaPay.',
      paidSeat: (amount, date) => `Paid: ${amount} on ${date}`,
      refundNone: 'No refund', refundPercent: 'Percent %', refundAmount: 'Exact amount',
      refundPreview: (value, remaining) => `Records a ${value} refund — ${remaining} is refundable`,
      refundInvalid: 'Enter a valid refund value.',
      refundTooBig: (remaining, currency) => `More than the refundable amount (${remaining} ${currency || 'EGP'}).`,
      noPayment: 'No payment is linked to this enrollment.',
      confirmCancel: 'Confirm un-enroll', cancelled: 'Enrollment cancelled.',
      errors: {
        reason_required: 'Write a reason.',
        already_cancelled: 'This enrollment is already cancelled.',
        no_payment_to_refund: 'There is no payment to refund.',
        refund_exceeds_payment: 'More than the refundable amount.',
        invalid_refund_amount: 'Invalid refund value.',
        invalid_refund_percent: 'The percent must be between 1 and 100.',
      },
    },
    instructors: {
      heading: 'Instructors', new: 'New instructor', edit: (name) => `Edit instructor — ${name}`,
      searchPlaceholder: 'Search name or email', search: 'Search',
      photo: 'Instructor photo', photoHint: 'JPG / PNG / WebP — shown on the public instructor page', removePhoto: 'Remove photo',
      uploadError: 'Unable to upload the image.',
      name: 'Name', email: 'Email', password: 'Password', newPassword: 'New password (optional)',
      phone: 'Phone (internal — never shown publicly)',
      headline: 'Professional title (shown under the name)',
      headlinePlaceholder: 'e.g. Professor at the Pyramids Reproduction Research Institute, equine consultant',
      section: 'Section', noSection: 'No section',
      bio: 'Bio (shown in full on the instructor page)',
      expertise: 'Expertise (comma separated)', expertisePlaceholder: 'Horses, reproduction, dairy farms',
      activeAccount: 'Account is active (listed publicly)',
      permissions: 'Video permissions', canAdd: 'Add video', canEdit: 'Edit video', canDelete: 'Delete video',
      columns: ['Instructor', 'Section', 'Courses', 'Missing from profile', 'Status', 'Actions'],
      complete: 'Complete', missing: { photo: 'photo', headline: 'title', bio: 'bio', expertise: 'expertise', section: 'section' },
      active: 'Active', inactive: 'Inactive', empty: 'No instructors yet.',
      deleteConfirm: (name) => `Delete ${name}?`,
      deactivate: 'Deactivate', activate: 'Activate',
      invalidEmail: 'Enter a valid email address — no extra words such as "email:".',
      deactivateConfirm: (name) => `Deactivate ${name}? They cannot sign in and disappear from the assignment pickers; their content is untouched.`,
      activateConfirm: (name) => `Activate ${name}?`,
      statusError: 'Unable to change the account status.',
      blockedByContent: (courses, videos) =>
        `Cannot delete: this instructor owns ${courses} course(s) and ${videos} video(s). Reassign them to another instructor first, or deactivate the account instead of deleting it.`,
    },
    users: {
      heading: 'Users', new: 'New user', edit: 'Edit user',
      filters: [['', 'All roles'], ['student', 'Student'], ['instructor', 'Instructor'], ['admin', 'Administrator']],
      roles: { student: 'Student', instructor: 'Instructor', admin: 'Administrator' }, searchPlaceholder: 'Search name or email', search: 'Search',
      name: 'Name', email: 'Email', password: 'Password', newPassword: 'New password (optional)', role: 'Role',
      activeAccount: 'Account is active', headline: 'Professional title (shown publicly)', bio: 'Bio', expertise: 'Expertise (comma separated)',
      instructorProfileHint: 'Photo, title, bio, expertise and section are managed on the Instructors page.',
      active: 'Active', inactive: 'Inactive', activate: 'Activate', deactivate: 'Deactivate', empty: 'No results.',
      deleteConfirm: (name) => `Delete ${name}?`, columns: ['Name', 'Email', 'Role', 'Status', 'Actions'],
    },
    messages: {
      heading: 'Messages', unread: 'unread', empty: 'No messages.', noSubject: '(No subject)',
      markRead: 'Mark as read', markUnread: 'Mark as unread', reply: 'Reply by email', deleteConfirm: 'Delete this message?',
    },
    settings: {
      heading: 'Site settings', subtitle: 'Public website content updates immediately after you save.',
      saved: 'Saved', saveError: 'Unable to save.', save: 'Save settings',
    },
    list: {
      add: '+ Add', empty: 'No items yet.', order: 'Order', actions: 'Actions', edit: 'Edit', delete: 'Delete',
      addTitle: 'Add item', editTitle: 'Edit item', save: 'Save', cancel: 'Cancel',
      moveUp: (name) => `Move ${name} up`, moveDown: (name) => `Move ${name} down`,
    },
  },
};

export function pageCopy(page, language = 'ar') {
  return COPY[language]?.[page] || COPY.ar[page] || {};
}
