"""book summaries

The books table only. Autogenerate again proposed the unrelated constraint drops described
in b29d593410bf; removed by hand.

Revision ID: 2a4f7036ea19
Revises: 478789c91842
Create Date: 2026-09-19 19:26:53.397063

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2a4f7036ea19'
down_revision = '478789c91842'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('books',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=250), nullable=False),
    sa.Column('title_en', sa.String(length=250), nullable=True),
    sa.Column('slug', sa.String(length=280), nullable=False),
    sa.Column('book_author', sa.String(length=200), nullable=True),
    sa.Column('excerpt', sa.String(length=1000), nullable=True),
    sa.Column('excerpt_en', sa.String(length=1000), nullable=True),
    sa.Column('cover', sa.String(length=500), nullable=True),
    sa.Column('pdf_path', sa.String(length=500), nullable=True),
    sa.Column('pdf_pages', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_books_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_books_status'), ['status'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('books', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_books_status'))
        batch_op.drop_index(batch_op.f('ix_books_slug'))

    op.drop_table('books')
    # ### end Alembic commands ###
