"""device swap policy

These tables/columns only. Autogenerate again proposed the unrelated constraint drops
described in b29d593410bf; removed by hand.

Revision ID: 478789c91842
Revises: a2237e7bec9b
Create Date: 2026-09-19 01:08:26.153036

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '478789c91842'
down_revision = 'a2237e7bec9b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('device_swap_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('reason', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=16), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('decided_by_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['decided_by_id'], ['users.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('device_swap_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_device_swap_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_device_swap_requests_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('device_swaps_used', sa.Integer(), server_default='0', nullable=False))
        batch_op.add_column(sa.Column('device_swap_window_start', sa.DateTime(timezone=True), nullable=True))
        batch_op.add_column(sa.Column('device_swap_grants', sa.Integer(), server_default='0', nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('device_swap_grants')
        batch_op.drop_column('device_swap_window_start')
        batch_op.drop_column('device_swaps_used')

    with op.batch_alter_table('device_swap_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_device_swap_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_device_swap_requests_status'))

    op.drop_table('device_swap_requests')
    # ### end Alembic commands ###
