"""videos directly under course (lessons.course_id, module_id nullable)

Revision ID: 49ad88f02a93
Revises: 5f11ded483da
Create Date: 2026-07-26 14:58:33.676255

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '49ad88f02a93'
down_revision = '5f11ded483da'
branch_labels = None
depends_on = None


def _foreign_key_name(table_name, column_name):
    for foreign_key in sa.inspect(op.get_bind()).get_foreign_keys(table_name):
        if foreign_key["constrained_columns"] == [column_name]:
            return foreign_key["name"]
    raise ValueError(f"foreign key for {table_name}.{column_name} was not found")


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('course_id', sa.Integer(), nullable=True))
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_lessons_course_id'), ['course_id'], unique=False)
        batch_op.create_foreign_key('fk_lessons_course_id_courses', 'courses', ['course_id'], ['id'])

    # ### end Alembic commands ###

    # Backfill: point existing videos at their course (via their legacy module).
    op.execute("""
        UPDATE lessons SET course_id = cm.course_id
        FROM course_modules cm
        WHERE lessons.module_id = cm.id AND lessons.course_id IS NULL
    """)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_constraint(_foreign_key_name('lessons', 'course_id'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_lessons_course_id'))
        batch_op.alter_column('module_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('course_id')

    # ### end Alembic commands ###
