"""contract gaps: phone, access_days, expires_at, renewal/bundle payment kinds, bundles, user_devices, i18n _en fields

Revision ID: 4f66f6ed2f30
Revises: 9a330821212b
Create Date: 2026-07-24 23:19:44.517578

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4f66f6ed2f30'
down_revision = '9a330821212b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('bundles',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('slug', sa.String(length=220), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('description_en', sa.Text(), nullable=True),
    sa.Column('image', sa.String(length=500), nullable=True),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('access_days', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_bundles_slug'), ['slug'], unique=True)
        batch_op.create_index(batch_op.f('ix_bundles_status'), ['status'], unique=False)

    op.create_table('user_devices',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=False),
    sa.Column('label', sa.String(length=160), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_seen', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'device_id', name='uq_device_user_device')
    )
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_devices_user_id'), ['user_id'], unique=False)

    op.create_table('bundle_courses',
    sa.Column('bundle_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('bundle_id', 'course_id')
    )
    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=250), nullable=True))
        batch_op.add_column(sa.Column('excerpt_en', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('body_en', sa.Text(), nullable=True))

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.add_column(sa.Column('name_en', sa.String(length=120), nullable=True))

    with op.batch_alter_table('course_modules', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=200), nullable=True))

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=200), nullable=True))
        batch_op.add_column(sa.Column('description_en', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('access_days', sa.Integer(), nullable=True))

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True))

    with op.batch_alter_table('instapay_payments', schema=None) as batch_op:
        batch_op.add_column(sa.Column('bundle_id', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('kind', sa.String(length=20), server_default='enroll', nullable=False))
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=True)
        batch_op.create_index(batch_op.f('ix_instapay_payments_bundle_id'), ['bundle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instapay_payments_kind'), ['kind'], unique=False)
        batch_op.create_foreign_key(None, 'bundles', ['bundle_id'], ['id'])

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('title_en', sa.String(length=200), nullable=True))

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('phone', sa.String(length=40), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('phone')

    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_column('title_en')

    with op.batch_alter_table('instapay_payments', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_instapay_payments_kind'))
        batch_op.drop_index(batch_op.f('ix_instapay_payments_bundle_id'))
        batch_op.alter_column('course_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.drop_column('kind')
        batch_op.drop_column('bundle_id')

    with op.batch_alter_table('enrollments', schema=None) as batch_op:
        batch_op.drop_column('expires_at')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_column('access_days')
        batch_op.drop_column('description_en')
        batch_op.drop_column('title_en')

    with op.batch_alter_table('course_modules', schema=None) as batch_op:
        batch_op.drop_column('title_en')

    with op.batch_alter_table('categories', schema=None) as batch_op:
        batch_op.drop_column('name_en')

    with op.batch_alter_table('articles', schema=None) as batch_op:
        batch_op.drop_column('body_en')
        batch_op.drop_column('excerpt_en')
        batch_op.drop_column('title_en')

    op.drop_table('bundle_courses')
    with op.batch_alter_table('user_devices', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_devices_user_id'))

    op.drop_table('user_devices')
    with op.batch_alter_table('bundles', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_bundles_status'))
        batch_op.drop_index(batch_op.f('ix_bundles_slug'))

    op.drop_table('bundles')
    # ### end Alembic commands ###
