"""fawaterk payments table

Revision ID: 5f11ded483da
Revises: a88d6d924eae
Create Date: 2026-07-26 11:45:11.104503

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5f11ded483da'
down_revision = 'a88d6d924eae'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('kind', sa.String(length=20), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('bundle_id', sa.Integer(), nullable=True),
    sa.Column('amount', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('gateway', sa.String(length=20), nullable=False),
    sa.Column('invoice_id', sa.String(length=40), nullable=True),
    sa.Column('invoice_key', sa.String(length=80), nullable=True),
    sa.Column('payment_method', sa.String(length=60), nullable=True),
    sa.Column('reference_number', sa.String(length=80), nullable=True),
    sa.Column('pay_url', sa.String(length=500), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['bundle_id'], ['bundles.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payments_bundle_id'), ['bundle_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_invoice_id'), ['invoice_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_payments_status'))
        batch_op.drop_index(batch_op.f('ix_payments_invoice_id'))
        batch_op.drop_index(batch_op.f('ix_payments_course_id'))
        batch_op.drop_index(batch_op.f('ix_payments_bundle_id'))

    op.drop_table('payments')
    # ### end Alembic commands ###
