"""completion certificates

The completion_certificates table only. Autogenerate again proposed dropping the unique
constraints on certificates.serial, learning_paths.slug, video_playback_events.client_event_id
and video_playback_sessions.public_id (pre-existing naming drift, see b29d593410bf); removed.

Revision ID: a2237e7bec9b
Revises: b29d593410bf
Create Date: 2026-09-16 19:02:05.077065

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a2237e7bec9b'
down_revision = 'b29d593410bf'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('completion_certificates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('serial', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('issued_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id', 'course_id', name='uq_completion_certificate_user_course')
    )
    with op.batch_alter_table('completion_certificates', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_completion_certificates_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_completion_certificates_serial'), ['serial'], unique=True)
        batch_op.create_index(batch_op.f('ix_completion_certificates_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('completion_certificates', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_completion_certificates_user_id'))
        batch_op.drop_index(batch_op.f('ix_completion_certificates_serial'))
        batch_op.drop_index(batch_op.f('ix_completion_certificates_course_id'))

    op.drop_table('completion_certificates')
    # ### end Alembic commands ###
