"""content access tiers (access_type) + baytarian verification (is_baytarian, baytarian_requests)

Revision ID: a88d6d924eae
Revises: 4f66f6ed2f30
Create Date: 2026-07-25 00:14:01.229586

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a88d6d924eae'
down_revision = '4f66f6ed2f30'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('baytarian_requests',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('documents', sa.JSON(), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('reject_reason', sa.String(length=300), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('baytarian_requests', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_baytarian_requests_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_baytarian_requests_user_id'), ['user_id'], unique=False)

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.add_column(sa.Column('access_type', sa.String(length=20), server_default='general', nullable=False))
        batch_op.create_index(batch_op.f('ix_courses_access_type'), ['access_type'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('is_baytarian', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###

    # Backfill existing courses: paid -> general, free -> free.
    op.execute("UPDATE courses SET access_type = CASE WHEN price > 0 THEN 'general' ELSE 'free' END")


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('is_baytarian')

    with op.batch_alter_table('courses', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_courses_access_type'))
        batch_op.drop_column('access_type')

    with op.batch_alter_table('baytarian_requests', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_baytarian_requests_user_id'))
        batch_op.drop_index(batch_op.f('ix_baytarian_requests_status'))

    op.drop_table('baytarian_requests')
    # ### end Alembic commands ###
