"""library rank: pin videos to the front of the public library

Written by hand rather than autogenerated. Autogenerate on this schema still proposes
dropping unique constraints on certificates.serial, learning_paths.slug and two video
session columns -- pre-existing drift, noted on the two previous migrations, and not
something to ship as a passenger on an unrelated change.

Revision ID: b148cdf18f16
Revises: 4727d613c9a5
"""
from alembic import op
import sqlalchemy as sa


revision = 'b148cdf18f16'
down_revision = '4727d613c9a5'
branch_labels = None
depends_on = None


def upgrade():
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.add_column(sa.Column('library_rank', sa.Integer(), nullable=True))
        batch_op.create_index(batch_op.f('ix_lessons_library_rank'), ['library_rank'], unique=False)


def downgrade():
    with op.batch_alter_table('lessons', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_lessons_library_rank'))
        batch_op.drop_column('library_rank')
