"""course exams, questions, options and attempts

Exam tables only. Autogenerate also proposed dropping unique constraints on
certificates.serial, learning_paths.slug, video_playback_events.client_event_id and
video_playback_sessions.public_id, plus swapping an index on user_devices. None of that
belongs to this change: the constraints exist in the database under names the models do
not declare, so the comparison read them as deletions. Dropping them would have allowed
duplicate certificate serials and broken playback event dedupe. Removed by hand.

Revision ID: b29d593410bf
Revises: c5b18ad3f402
Create Date: 2026-09-16 00:04:43.952068

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b29d593410bf'
down_revision = 'c5b18ad3f402'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('course_exams',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=True),
    sa.Column('title_en', sa.String(length=200), nullable=True),
    sa.Column('pass_percent', sa.Integer(), server_default='70', nullable=False),
    sa.Column('is_published', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('course_id', name='uq_exam_course')
    )
    with op.batch_alter_table('course_exams', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_course_exams_course_id'), ['course_id'], unique=False)

    op.create_table('exam_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('score_percent', sa.Integer(), nullable=False),
    sa.Column('correct_count', sa.Integer(), nullable=False),
    sa.Column('question_count', sa.Integer(), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=False),
    sa.Column('submitted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['exam_id'], ['course_exams.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_attempts_exam_id'), ['exam_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_attempts_passed'), ['passed'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_attempts_submitted_at'), ['submitted_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_attempts_user_id'), ['user_id'], unique=False)

    op.create_table('exam_questions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('exam_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=True),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['exam_id'], ['course_exams.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_questions_exam_id'), ['exam_id'], unique=False)

    op.create_table('exam_options',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=False),
    sa.Column('text', sa.Text(), nullable=False),
    sa.Column('text_en', sa.Text(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), server_default='false', nullable=False),
    sa.Column('position', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_options', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_options_question_id'), ['question_id'], unique=False)

    op.create_table('exam_attempt_answers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('attempt_id', sa.Integer(), nullable=False),
    sa.Column('question_id', sa.Integer(), nullable=True),
    sa.Column('option_id', sa.Integer(), nullable=True),
    sa.Column('is_correct', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['attempt_id'], ['exam_attempts.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['option_id'], ['exam_options.id'], ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['question_id'], ['exam_questions.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('exam_attempt_answers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_exam_attempt_answers_attempt_id'), ['attempt_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_attempt_answers_option_id'), ['option_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_exam_attempt_answers_question_id'), ['question_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    with op.batch_alter_table('exam_attempt_answers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_attempt_answers_question_id'))
        batch_op.drop_index(batch_op.f('ix_exam_attempt_answers_option_id'))
        batch_op.drop_index(batch_op.f('ix_exam_attempt_answers_attempt_id'))

    op.drop_table('exam_attempt_answers')
    with op.batch_alter_table('exam_options', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_options_question_id'))

    op.drop_table('exam_options')
    with op.batch_alter_table('exam_questions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_questions_exam_id'))

    op.drop_table('exam_questions')
    with op.batch_alter_table('exam_attempts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_exam_attempts_user_id'))
        batch_op.drop_index(batch_op.f('ix_exam_attempts_submitted_at'))
        batch_op.drop_index(batch_op.f('ix_exam_attempts_passed'))
        batch_op.drop_index(batch_op.f('ix_exam_attempts_exam_id'))

    op.drop_table('exam_attempts')
    with op.batch_alter_table('course_exams', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_course_exams_course_id'))

    op.drop_table('course_exams')
    # ### end Alembic commands ###
