"""instapay: account whitelist + payment submissions

Revision ID: c3524eebd876
Revises: 9e617df3a9bc
Create Date: 2026-07-12 23:23:52.445086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c3524eebd876'
down_revision = '9e617df3a9bc'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('instapay_account',
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('account_name', sa.String(length=160), nullable=False),
    sa.Column('number', sa.String(length=40), nullable=True),
    sa.Column('url', sa.String(length=200), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.PrimaryKeyConstraint('account_id')
    )
    op.create_table('instapay_payments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('image_path', sa.String(length=500), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('reference', sa.String(length=40), nullable=True),
    sa.Column('transfer_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('total_amount', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('fees', sa.Numeric(precision=10, scale=2), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('tx_date_text', sa.String(length=60), nullable=True),
    sa.Column('note', sa.String(length=500), nullable=True),
    sa.Column('sender_name', sa.String(length=160), nullable=True),
    sa.Column('sender_account', sa.String(length=160), nullable=True),
    sa.Column('receiver_account', sa.String(length=160), nullable=True),
    sa.Column('receiver_hash', sa.String(length=160), nullable=True),
    sa.Column('transaction_approved', sa.String(length=40), nullable=True),
    sa.Column('ogs_account_found', sa.String(length=20), nullable=True),
    sa.Column('is_total_amount_correct', sa.Boolean(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('reviewed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('reject_reason', sa.String(length=300), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('instapay_payments', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_instapay_payments_course_id'), ['course_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_instapay_payments_reference'), ['reference'], unique=False)
        batch_op.create_index(batch_op.f('ix_instapay_payments_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_instapay_payments_user_id'), ['user_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('instapay_payments', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_instapay_payments_user_id'))
        batch_op.drop_index(batch_op.f('ix_instapay_payments_status'))
        batch_op.drop_index(batch_op.f('ix_instapay_payments_reference'))
        batch_op.drop_index(batch_op.f('ix_instapay_payments_course_id'))

    op.drop_table('instapay_payments')
    op.drop_table('instapay_account')
    # ### end Alembic commands ###
