"""instructor video permission flags on users

Revision ID: f4189222bd6a
Revises: 4751c3bfc91d
Create Date: 2026-07-13 19:32:15.912511

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f4189222bd6a'
down_revision = '4751c3bfc91d'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('can_add_video', sa.Boolean(), server_default=sa.text('true'), nullable=False))
        batch_op.add_column(sa.Column('can_edit_video', sa.Boolean(), server_default=sa.text('false'), nullable=False))
        batch_op.add_column(sa.Column('can_delete_video', sa.Boolean(), server_default=sa.text('false'), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('can_delete_video')
        batch_op.drop_column('can_edit_video')
        batch_op.drop_column('can_add_video')

    # ### end Alembic commands ###
